-
  name: setup database
  hosts: database
  become: yes
  tasks:
    - name: Install MariaDB server
      yum:
        name: mariadb-server
        state: latest
    - name: Install firewall
      yum:
        name: firewalld
        state: latest
    - name: Enable and start MariaDB server
      service:
        name: mariadb
        enabled: true
        state: started
    - name: Enable and start firewall
      service:
        name: firewalld
        enabled: true
        state: started
    - name: configure firewall
      command: firewall-cmd --permanent --zone=public --add-port=3306/tcp
    - name: reload firewall
      command: firewall-cmd --reload
    - name: Configure database
      mysql_db:
        name: ecomdb
        state: present
    - name: Configure database user
      mysql_user:
        name: ecomuser
        password: ecompassword
        priv: '*.*:ALL,GRANT'
        host: 192.168.0.189
        state: present
    - name: Restart database to effect changes
      service:
        name: mariadb
        state: restarted
    - name: Copy db
      copy:
        src: db-load-script.sql
        dest: /tmp/db-load-script.sql
    - name: Load database
      mysql_db:
        name: all
        state: import
        target: /tmp/db-load-script.sql
-
  name: Setup web server
  hosts: webserver
  become: yes
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Install php
      yum:
        name: php
        state: latest
    - name: install php-mysql
      yum:
        name: php-mysql
        state: latest
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
    - name: Install git
      yum:
        name: git
        state: latest
    - name: Enable and start firewall
      service:
        name: firewalld
        enabled: true
        state: started
    - name: Enable and start httpd
      service:
        name: httpd
        enabled: true
        state: started
    - name: configure firewall
      command: firewall-cmd --permanent --zone=public --add-port=80/tcp
    - name: reload firewall
      command: firewall-cmd --reload
    - name: change default page to index.php
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: 'index.html'
        replace: 'index.php'
    - name: download code
      git:
        repo: https://github.com/kodekloudhub/learning-app-ecommerce.git
        dest: /var/www/html/
        clone: yes
        force: yes
    - name: update index.php to connect to the right database server
      replace:
        path: /var/www/html/index.php
        regexp: '172.20.1.101'
        replace: '192.168.0.61'
